export const emptyDogStatus = {
  source: null,
  statusFresh: false,
  slaveLat: null,
  slaveLon: null,
  masterLat: null,
  masterLon: null,
  distanceMeters: null,
  speedKmh: null,
  satellites: null,
  hdop: null,
  activity: null,
  activityValid: false,
  batteryMillivolts: null,
  batteryPercentage: null,
  batteryValid: false,
  masterBatteryMillivolts: null,
  masterBatteryPercentage: null,
  masterBatteryValid: false,
  rssi: null,
  snr: null,
  gpsTime: null,
  activityTime: null,
  type: null,
  sequence: null,
  length: null,
};

export function toDogStatus(data) {
  const value = data || {};
  return {
    source: value.source ?? null,
    statusFresh: Boolean(value.status_fresh ?? value.s),
    slaveLat: value.slave_lat ?? value.slat ?? value.lat ?? null,
    slaveLon: value.slave_lon ?? value.slon ?? value.lon ?? null,
    masterLat: value.master_lat ?? value.mlat ?? null,
    masterLon: value.master_lon ?? value.mlon ?? null,
    distanceMeters: value.distance_m ?? value.dst ?? null,
    speedKmh: value.speed_kmh ?? value.spd ?? null,
    satellites: value.sat ?? null,
    hdop: value.hdop ?? value.hd ?? null,
    activity: value.activity ?? value.act ?? null,
    activityValid: Boolean(value.activity_valid ?? value.av),
    batteryMillivolts: value.battery_mv ?? value.bmv ?? null,
    batteryPercentage: value.battery_pct ?? value.bp ?? null,
    batteryValid: Boolean(value.battery_valid ?? value.bv),
    masterBatteryMillivolts: value.master_battery_mv ?? value.mbmv ?? null,
    masterBatteryPercentage: value.master_battery_pct ?? value.mbp ?? null,
    masterBatteryValid: Boolean(value.master_battery_valid ?? value.mbv),
    rssi: value.rssi ?? null,
    snr: value.snr ?? null,
    gpsTime: value.gps_time ?? value.gt ?? null,
    activityTime: value.activity_time ?? value.at ?? null,
    type: value.type ?? null,
    sequence: value.seq ?? null,
    length: value.len ?? null,
  };
}
